server:
  port: 8091

spring:
  application:
    name: itcast-zuul

zuul:
  routes:
    service-provider: /service-provider/** #路由名称，可以随便写，习惯上是服务名
    service-consumer: /consumer/**
      #第一种 第二种 path: /service-provider/**
      #第一种 url: http://localhost:8081
      #第二种 serviceId: service-provider
      #现在的最终结果为第三种，经常使用
      #不配置，可以使用服务名+路径进行访问
  prefix: /api #推荐使用，可以不配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
