server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql:///jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  application:
    name: service-provider
mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.cy.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
    register-with-eureka: true #消费者启动时会检测该参数是否为true，为true进行注册
  instance:
    lease-renewal-interval-in-seconds: 10 #续约时间
    lease-expiration-duration-in-seconds: 20 #失效时间
