server:
  port: 8080
spring:
  application:
    name: service-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
    fetch-registry: true #消费者启动，会检测改参数是否为true,默认为true,拉取列表
    registry-fetch-interval-seconds: 10 #间隔多长时间拉取一次
#service-provider: #服务名称
  #ribbon:
    #NFloadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #设置负载均衡算法
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 #设置hystrix的超时时间为6000ms
feign:
  hystrix:
    enabled: true #默认关闭，打开hystrix
